# Background

<big> 
This was the capstone project for a machine learning class I took. The class covered the mathematical foundation of several machine learning models and during the course of the class, I had to build several machine learning models from scratch including principal component analysis (PCA), linear regression, logistic regression, and artificial neural network (ANN) models.

For the capstone project, I was given a dataset by the instructor and had to evaluate the models I built during the course of the class on the dataset. I also had to apply existing Scikit-learn packages that implement these models. This allowed me to validate the results I got using the models I built from scratch by comparing their results to those obtained using Scikit-learn packages.

This class gave me a solid background and introduction to machine learning models.

</big>

<br>

## About data:

<big> The data comprised 863 samples, 15606 independent variables, and two classes of target variables (0/1). </big>

<br>

### Independent variables

In [3]:
import pandas as pd

df_x = pd.read_csv("C:/Users/nnamd/Documents/data/machine_learning/sandbox_3/sample_data_for_project_final.csv")
df_x

,Unnamed: 0,sample_1,sample_2,sample_3,sample_4,sample_5,sample_6,sample_7,sample_8,sample_9,...,sample_855,sample_856,sample_857,sample_858,sample_859,sample_860,sample_861,sample_862,sample_863,sample_864
0,variable_1,1.335571e+05,4.067772e+05,4.653638e+05,2.327503e+05,3.204984e+05,9.507953e+04,2.629849e+05,1.677002e+05,1.651118e+05,...,3.331851e+05,4.848780e+05,2.804682e+05,5.179674e+05,4.358776e+05,3.139291e+05,3.904108e+05,3.532888e+05,5.979247e+05,4.931237e+05
1,variable_2,2.914323e+08,2.058200e+08,1.572093e+08,1.889364e+08,2.151381e+08,1.980727e+08,2.349494e+08,1.437654e+08,3.101801e+08,...,9.908329e+07,1.128658e+08,1.349937e+08,1.058415e+08,9.786954e+07,7.953481e+07,9.254447e+07,1.378881e+08,1.291880e+08,1.421230e+08
2,variable_3,1.039778e+08,6.959067e+07,6.546160e+07,7.890295e+07,1.099364e+08,9.149507e+07,1.177567e+08,7.226901e+07,1.280126e+08,...,5.433479e+07,4.719515e+07,5.444209e+07,4.031031e+07,5.985512e+07,2.243647e+07,6.748665e+07,5.571944e+07,8.007063e+07,7.203118e+07
3,variable_4,1.899937e+07,2.725515e+07,5.049965e+07,3.885274e+07,3.245649e+07,2.520913e+07,3.618445e+07,4.143107e+07,2.248020e+07,...,3.839418e+07,3.597201e+07,1.600624e+07,1.891379e+07,2.643795e+07,2.854334e+07,2.003175e+07,1.983767e+07,1.582618e+07,2.097925e+07
4,variable_5,1.075189e+04,1.365641e+02,5.717232e+03,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,3.150963e+03,1.365641e+02,...,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15601,variable_15602,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,4.849214e+03,2.647425e+03,1.365641e+02,5.857132e+03,...,1.365641e+02,1.382506e+03,1.365641e+02,8.669330e+03,3.338606e+03,1.826847e+03,9.233444e+03,6.235643e+03,1.074344e+04,9.022216e+03
15602,variable_15603,1.484041e+04,1.365641e+02,8.670437e+03,1.365641e+02,9.700260e+03,2.808402e+03,9.422814e+03,1.365641e+02,3.608028e+03,...,1.365641e+02,6.552061e+03,7.869005e+03,6.919266e+03,3.443958e+03,5.542762e+03,1.365641e+02,7.214279e+03,9.303027e+03,8.189856e+03
15603,variable_15604,3.509693e+03,6.338602e+03,9.574115e+03,1.731127e+03,9.168757e+03,1.365641e+02,3.158676e+03,7.219811e+03,7.749311e+03,...,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02
15604,variable_15605,1.365641e+02,2.799276e+03,6.296987e+03,1.365641e+02,4.886416e+03,1.365641e+02,6.012350e+03,6.212321e+03,5.120082e+03,...,6.193849e+03,1.365641e+02,5.575186e+03,4.901934e+03,5.794283e+03,7.640553e+03,4.356595e+03,1.365641e+02,9.194651e+03,5.405931e+03
15605,variable_15606,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,1.365641e+02,...,8.420486e+03,5.389534e+03,7.218614e+03,1.365641e+02,3.187292e+03,5.848782e+03,1.157885e+04,3.406270e+03,1.365641e+02,7.939925e+03

<br>

### Target variables

In [4]:
df_y = pd.read_csv("C:/Users/nnamd/Documents/data/machine_learning/sandbox_3/sample_metadata_for_project_final.csv")
df_y

    sample_name  sample_label
0      sample_1             0
1      sample_2             1
2      sample_3             0
3      sample_4             1
4      sample_5             0
..          ...           ...
858  sample_860             1
859  sample_861             0
860  sample_862             1
861  sample_863             0
862  sample_864             1

[863 rows x 2 columns]

<br>

## Project Goals: 

<big>
=> Dimensionality reduction of data using PCA and extraction of interesting principal components.

=> Using extracted principal components to build logistic regression and ANN models to predict the target variables in the data. 

<br>

- The next pages will show the application of PCA, logistic regression, and ANN models.

</big>